### ISSUE TITLE
Use allo before or after deduplication

### ISSUE THREAD

**Issue by QianhuiWan** [seqcode/allo#4]
Hello, I just have a question about the deduplication step. Is it better to apply allo after removing duplicates? Thank you! 
Best regards, 
Qianhui

**Comment by anmorrissey** [comment]
Hello, we believe it's best to deduplicate before using Allo. Assuming you're using Picard, the removal of duplicates will not work properly after allocation as the duplicates may be allocated to different locations. Let me know if you have any other questions!

**Comment by QianhuiWan** [comment]
> Hello, we believe it's best to deduplicate before using Allo. Assuming you're using Picard, the removal of duplicates will not work properly after allocation as the duplicates may be allocated to different locations. Let me know if you have any other questions!

Hi Lexi Morrissey, thank you for you answer! It's very helpful.
Best regards, Qianhui

**Comment by hukai916** [comment]
Hi @anmorrissey , is there a specific reason deduplication is recommended before running Allo? My understanding is that Allo's CNN was trained on raw BAM files straight from Bowtie, without deduplication. If that's correct, shouldn't the input BAM also be non-deduplicated, to match the training distribution?

A related concern: even if deduplication is recommended, the default Picard MarkDuplicates approach may not be well-suited here, since Picard identifies duplicates based on primary alignment position only. For multi-mapping reads with tied best-scoring alignments, Bowtie's choice of primary alignment is essentially an arbitrary pick. That could make duplicate-marking inconsistent if using Picard. A fastq-level deduplication might be more appropriate here. Please share any feedback you may have. Thanks!

**Comment by shaunmahony** [comment]
@hukai916 The original question asked if it is best to deduplicate before or after Allo, and the answer is that if deduplication needs to be done, it should be done before. This should not be taken as a blanket recommendation to always deduplicate before Allo - that should be left to the individual user and the specific use case. Please deduplicate as you see fit for your data.

**Comment by hukai916** [comment]
Thanks for the reply, can you confirm whether the Allo models were trained using BAMs without deduplication or not?
